### ISSUE TITLE
ws library is slightly out of date

### ISSUE THREAD

**Issue by treeform** [sunjohanday/xander#1]
Hey thanks for using my `ws` lib. 

I noticed that its slightly out of date. I have fixed some issues with it recently, I think you would like the updates: 

https://github.com/treeform/ws/commits/master

**Comment by santerijps** [comment]
Thanks for informing me! it has now been updated. [https://github.com/sunjohanday/xander/commit/ed5b5d3ad3443298979e6cb69ef2fbc57d05fb0a](https://github.com/sunjohanday/xander/commit/ed5b5d3ad3443298979e6cb69ef2fbc57d05fb0a)
