### ISSUE TITLE
error in running basic Xander-app example 

### ISSUE THREAD

**Issue by 52lemon** [sunjohanday/xander#2]
### here is it 
`
PS E:\NimProjects> nim c -r .\test_web.nim

Hint: used config file 'C:\nim\config\nim.cfg' [Conf]

Hint: system [Processing]

Hint: widestrs [Processing]

Hint: io [Processing]

Hint: test_web [Processing]

Hint: xander [Processing]

Hint: asyncnet [Processing]

Hint: asyncdispatch [Processing]

Hint: os [Processing]

Hint: strutils [Processing]

Hint: parseutils [Processing]

Hint: math [Processing]

Hint: bitops [Processing]

Hint: macros [Processing]

Hint: algorithm [Processing]

Hint: unicode [Processing]

Hint: pathnorm [Processing]

Hint: osseps [Processing]

Hint: winlean [Processing]

Hint: dynlib [Processing]

Hint: times [Processing]

Hint: options [Processing]

Hint: typetraits [Processing]

Hint: time_t [Processing]

Hint: tables [Processing]

Hint: hashes [Processing]

Hint: heapqueue [Processing]

Hint: lists [Processing]

Hint: asyncstreams [Processing]

Hint: asyncfutures [Processing]

Hint: deques [Processing]

Hint: cstrutils [Processing]

Hint: nativesockets [Processing]

Hint: net [Processing]

Hint: sets [Processing]

Hint: asynchttpserver [Processing]

Hint: uri [Processing]

Hint: httpcore [Processing]

Hint: cookies [Processing]

Hint: strtabs [Processing]

Hint: base64 [Processing]

Hint: httpclient [Processing]

Hint: mimetypes [Processing]

Hint: random [Processing]

Hint: streams [Processing]

Hint: asyncfile [Processing]

Hint: json [Processing]

Hint: lexbase [Processing]

Hint: parsejson [Processing]

Hint: logging [Processing]

C:\Users\yuchijin\.nimble\pkgs\xander-0.6.0\xander.nim(13, 3) Error: cannot open file: regex

PS E:\NimProjects>
`

**Comment by santerijps** [comment]
Have you tried installing the **regex** library? Xander depends on that library.

**Comment by 52lemon** [comment]
> Have you tried installing the **regex** library? Xander depends on that library.

yes,i did , and there still another error, after work, i will paste the wrong code

**Comment by santerijps** [comment]
Also try compiling your code with cpp, might work.

**Comment by 52lemon** [comment]
OK， i'll try with cpp, thanks

**Comment by santerijps** [comment]
closing for now
